# Generated by Django 5.1.6 on 2025-02-22 00:40

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FounderInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Founder Information',
                'verbose_name_plural': 'Founder Informations',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='DepositPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Working Hours')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_points', to='users.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Deposit Point',
                'verbose_name_plural': 'Deposit Points',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='users.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Quarter',
                'verbose_name_plural': 'Quarters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('date_found', models.DateField(null=True, verbose_name='Date Found')),
                ('status', models.CharField(choices=[('FOUND', 'Found'), ('LOST', 'Lost'), ('ARCHIVED', 'Archived')], default='LOST', max_length=10, verbose_name='Status')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('deposit_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.depositpoint', verbose_name='Deposit Point')),
                ('found_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='users.city', verbose_name='City where the document was found')),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documenttype', verbose_name='Document Type')),
                ('founder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.founderinformation', verbose_name='Founder')),
                ('found_quarter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.quarter', verbose_name='Quarter where the document was found')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='depositpoint',
            name='quarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_points', to='documents.quarter', verbose_name='Quarter'),
        ),
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='documents/images/%Y/%m/%d/', verbose_name='Image')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='documents.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Document Image',
                'verbose_name_plural': 'Document Images',
                'order_with_respect_to': 'document',
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-created_at'], name='documents_d_created_71dced_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', '-created_at'], name='documents_d_status_dead80_idx'),
        ),
    ]
