# Generated by Django 5.1.6 on 2025-02-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
