# Generated by Django 5.1.6 on 2025-02-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, verbose_name='Slug'),
        ),
    ]
